# Generated by Django 6.0 on 2026-01-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('km_atual', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manuntencao', 'Manuntenção')], default='disponivel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('km_saida', models.PositiveIntegerField()),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('km_retorno', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.veiculo')),
            ],
        ),
    ]
